server.port: 8084

spring:
  application.name: notification-service
  kafka:
    bootstrap-servers: localhost:9092
    group-id: notification-group
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
    properties:
      schema.registry.url: http://127.0.0.1:8085
      specific.avro.reader: true

  mail:
    host: localhost
    port: 1025
    username: hospital.demo-support@gmail.com
    password: password
    properties:
      mail:
        smtp:
          ssl.trust: "*"
          auth: true
          starttls.enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
    tags:
      application: Notification Service
  observations:
    key-values:
      application: notification-service
  tracing:
    sampling:
      probability: 1.0