version: '4'

services:
  mongo:
    image: mongo:7.0
    container_name: shopping-mongodb-container
    restart: no
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: product_db
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: