version: '4'

services:
  postgres:
    image: postgres:17.2-alpine
    container_name: shopping-order-postgres-container
    restart: no
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: order_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: