---
server:
  port:
    8081

spring:
  application:
    name: order-service
  jpa:
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: none
    properties:
      hibernate:
        generate_statistics: false
        format_sql: true
  flyway:
    enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/order_db
    username: admin
    password: password
    driver-class-name: org.postgresql.Driver
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

inventory:
  url: http://localhost:8082