server:
  port:
    8080

spring:
  data:
    mongodb:
      uri: mongodb://admin:password@localhost:27017/product_db?authSource=admin
      uuid-representation: standard

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs