---
server:
  port:
    8082

spring:
  application:
    name: inventory-service
  jpa:
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: none
    properties:
      hibernate:
        generate_statistics: false
        format_sql: true
  flyway:
    enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/inventory_db
    username: admin
    password: password
    driver-class-name: org.postgresql.Driver

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
    tags:
      application: Inventory Service
  observations:
    key-values:
      application: inventory-service
  tracing:
    sampling:
      probability: 1.0

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

loki:
  url: http://localhost:3100/loki/api/v1/push