apiVersion: v1
kind: Pod
metadata:
  name: shopping-maildev
  labels:
    app: maildev
spec:
  containers:
    - name: maildev
      image: maildev/maildev:2.2.1
      ports:
        - containerPort: 1080
          name: http
        - containerPort: 1025
          name: smtp
---
apiVersion: v1
kind: Service
metadata:
  name: shopping-maildev-service
  labels:
    app: maildev
spec:
  selector:
    app: maildev
  ports:
    - name: http
      protocol: TCP
      port: 1080
      targetPort: 1080
    - name: smtp
      protocol: TCP
      port: 1025
      targetPort: 1025
  type: NodePort
